# Sonokai

set -g mode-style "fg=#76cce0,bg=#414550"

set -g message-style "fg=#76cce0,bg=#414550"
set -g message-command-style "fg=#76cce0,bg=#414550"

set -g pane-border-style "fg=#414550"
set -g pane-active-border-style "fg=#76cce0"

set -g status-style "fg=#76cce0,bg=#2c2e34"

set -g status-left "#[fg=#2c2e34,bg=#76cce0,bold] #S #[fg=#76cce0,bg=#2c2e34,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#2c2e34,bg=#2c2e34,nobold,nounderscore,noitalics]#[fg=#76cce0,bg=#2c2e34] #{prefix_highlight} #(agent-manager --status --icon-color=#b39df3 --approval-color=#fc5d7c --finished-color=#76cce0 --working-color=#e7c664 --waiting-color=#9ed072)#[fg=#414550,bg=#2c2e34,nobold,nounderscore,noitalics]#[fg=#76cce0,bg=#414550] %Y-%m-%d  %I:%M %p #[fg=#76cce0,bg=#414550,nobold,nounderscore,noitalics]#[fg=#2c2e34,bg=#76cce0,bold] #h "
if-shell '[ "$(tmux show-option -gqv "clock-mode-style")" == "24" ]' {
  set -g status-right "#[fg=#2c2e34,bg=#2c2e34,nobold,nounderscore,noitalics]#[fg=#76cce0,bg=#2c2e34] #{prefix_highlight} #(agent-manager --status --icon-color=#b39df3 --approval-color=#fc5d7c --finished-color=#76cce0 --working-color=#e7c664 --waiting-color=#9ed072)#[fg=#414550,bg=#2c2e34,nobold,nounderscore,noitalics]#[fg=#76cce0,bg=#414550] %Y-%m-%d  %H:%M #[fg=#76cce0,bg=#414550,nobold,nounderscore,noitalics]#[fg=#2c2e34,bg=#76cce0,bold] #h "
}

setw -g window-status-activity-style "underscore,fg=#7f8490,bg=#2c2e34"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#7f8490,bg=#2c2e34"
setw -g window-status-format "#[fg=#2c2e34,bg=#2c2e34,nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=#2c2e34,bg=#2c2e34,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#2c2e34,bg=#414550,nobold,nounderscore,noitalics]#[fg=#76cce0,bg=#414550,bold] #I  #W #F #[fg=#414550,bg=#2c2e34,nobold,nounderscore,noitalics]"

set -g @prefix_highlight_output_prefix "#[fg=#e7c664]#[bg=#2c2e34]#[fg=#2c2e34]#[bg=#e7c664]"
set -g @prefix_highlight_output_suffix ""
